# Admins (also pulled from .env)
ADMIN_IDS_DEFAULT = [8055058352, 7200774078]

ASSET_CLASSES = ["CURRENCY PAIRS", "METALS", "INDICES", "ENERGIES", "CRYPTO"]

CURRENCY_PAIRS = [
    "EUR/USD","GBP/USD","USD/JPY","USD/CHF","AUD/USD","USD/CAD",
    "NZD/USD","EUR/JPY","GBP/JPY","EUR/GBP","AUD/JPY","EUR/CHF"
]
SINGLE_INSTRUMENTS = {
    "METALS": ["XAU/USD"],
    "INDICES": ["NAS100 / US_TECH"],
    "ENERGIES": ["WTI / USOIL"],
    "CRYPTO": ["BTC/USD"]
}

# News categories
NEWS_CATEGORIES = ["Geopolitical Events", "Central Bank News (Fed, ECB)", "Inflation & Economic Data"]

# Legal & Scripts (word-for-word; escaped at send time)
TERMS_AND_CONDITIONS = (
    "Welcome to the 𝕸𝕴𝕲𝕺𝕾 𝕭.™ premium service. By proceeding, you agree to the following legally binding terms:\n"
    "1.Service Provided: You authorize this bot to connect to your specified MT5 trading account via a secure MetaApi token for the sole purpose of executing and managing trades based on the proprietary migosconcept$ strategy.\n"
    "2.Profit Sharing Agreement: In exchange for this service, you agree to a 20% profit-sharing model. This fee is calculated based on the net profit generated by the bot's trades on your account. You are responsible for remitting this payment upon request. Failure to comply will result in immediate and permanent termination of service.\n"
    "3.Risk Acknowledgement: You understand that all trading, including automated trading, involves substantial risk of loss and is not suitable for every investor. You acknowledge that past performance is not indicative of future results.\n"
    "4.No Financial Advice: The service and its signals are for educational and informational purposes only. The owner (\"Migos\") and the bot are not financial advisors. You are solely responsible for all trading decisions and their outcomes on your account.\n"
    "5.Limitation of Liability: We are not liable for any losses incurred due to market volatility, technical issues (including platform or internet connectivity failures), or unforeseen events. The bot's \"Cool-Down\" and \"Invalidation\" protocols are safeguards, not guarantees against loss.\n"
    "By clicking 'I Agree & Accept', you confirm that you have read, understood, and accepted these terms in their entirety."
)

GENERAL_RISK = (
    "Trading foreign exchange, indices, commodities, and cryptocurrencies on margin carries a high level of risk and may not be suitable for all individuals. "
    "The high degree of leverage can work against you as well as for you. Before deciding to trade, you should carefully consider your investment objectives, level of experience, and risk appetite. "
    "The possibility exists that you could sustain a loss of some or all of your initial investment and therefore you should not invest money that you cannot afford to lose. "
    "Any opinions, news, research, analyses, prices, or other information contained within this bot are provided as general market commentary and do not constitute investment advice. "
    "The owner of this bot will not accept liability for any loss or damage, including without limitation to, any loss of profit, which may arise directly or indirectly from use of or reliance on such information. "
    "You are solely responsible for your own trading decisions."
)

HIGH_IMPACT_CAUTION = (
    "CAUTION: A high-impact news event is scheduled for release shortly. To protect capital from extreme volatility, all signal generation is paused. "
    "We will resume analysis 30 minutes after the event."
)

POST_NEWS_WAITING = (
    "The market is currently consolidating post-news. I am actively analyzing the charts, waiting for a clear structure and a high-probability migosconcept$ setup to form. "
    "PATIENCE ✰ DISCIPLINE ✰ RISK MANAGEMENT"
)

COOLDOWN_MSG = (
    "Dear {name}, we've hit a few consecutive losses. To protect your capital and avoid unfavorable market conditions, I will be pausing trading on your account for today. "
    "We will resume with fresh analysis tomorrow. PATIENCE ✰ DISCIPLINE ✰ RISK MANAGEMENT"
)

UNAUTHORIZED_ADMIN = (
    "This action is denied. The requested command is for admin use only. "
    "For assistance, please contact @Bank_rats | @Migos_B_Fx254."
)

GROUP_WELCOME = (
    "Hello {name}! Welcome to {group}. I am the 𝕸𝕴𝕲𝕺𝕾 𝕭.™, your trading assistant. "
    "To get started and access my features, please register with me."
)

SIGNAL_TEMPLATE = (
    "🟢 READY SIGNAL: BUY 🟢\n"
    "Disclaimer: This is not financial advice. Please conduct your own analysis. If you are seeing this alert more than 5 minutes after it was sent, consider waiting for the next opportunity. You are solely responsible for your trading decisions.\n"
    "BUY At: {entry}\n"
    "Target 1: {tp1} ({tp1_pips} Pips)\n"
    "Target 2: {tp2} ({tp2_pips} Pips)\n"
    "Target 3: {tp3} ({tp3_pips} Pips)\n"
    "🛑 Stop-Loss: {sl} ({sl_pips} Pips)\n"
    "PATIENCE ✰ DISCIPLINE ✰ RISK MANAGEMENT"
)

TARGET_HIT_TEMPLATE = (
    "🎉 TARGET {num} HIT! 🎉 on our {pair} trade! We've just bagged {pips} pips of profit. "
    "Action Required: If you are managing this trade manually, now is a great time to secure partial profits and move your Stop-Loss to Break-Even (BE) to make the rest of the trade risk-free!"
)
