from config.settings import BRAND, PAYMENTS

FOOTER = "\n\n" + BRAND["footer"]

WELCOME = (
    "Hello\\! I am the *𝕸𝕴𝕲𝕺𝕾 𝕭\\.™*, your 24/7 Digital Trading Twin\\.\n"
    "To get started, please register\\."
) + FOOTER

BOT_PUBLIC_DESC = BRAND["bot_public_desc"]

TERMS = (
"Welcome to the *𝕸𝕴𝕲𝕺𝕾 𝕭\\.™* premium service\\. By proceeding, you agree to the following legally binding terms:\n"
"1\\. *Service Provided*: You authorize this bot to connect to your specified MT4/MT5 trading account for the sole purpose of executing and managing trades based on the proprietary migosconcept\\$ strategy\\.\n"
"2\\. *Profit Sharing Agreement*: In exchange for this service, you agree to a 20% profit\\-sharing model\\. This fee is calculated based on the net profit generated by the bot's trades on your account\\. You are responsible for remitting this payment upon request\\. Failure to comply will result in immediate and permanent termination of service\\.\n"
"3\\. *Risk Acknowledgement*: You understand that all trading, including automated trading, involves substantial risk of loss and is not suitable for every investor\\. You acknowledge that past performance is not indicative of future results\\.\n"
"4\\. *No Financial Advice*: The service and its signals are for educational and informational purposes only\\. The owner \\(\"Migos\"\\) and the bot are not financial advisors\\. You are solely responsible for all trading decisions and their outcomes on your account\\.\n"
"5\\. *Limitation of Liability*: We are not liable for any losses incurred due to market volatility, technical issues \\(including platform or internet connectivity failures\\), or unforeseen events\\. The bot's \"Cool\\-Down\" and \"Invalidation\" protocols are safeguards, not guarantees against loss\\.\n"
"By clicking *I Agree & Accept*, you confirm that you have read, understood, and accepted these terms in their entirety\\."
) + FOOTER

DISCLAIMER = (
"⚠️ *Risk Disclaimer:*\n"
"Trading foreign exchange, indices, commodities, and cryptocurrencies on margin carries a high level of risk and may not be suitable for all individuals\\. "
"Consider your objectives, level of experience, and risk appetite before engaging in these markets\\. "
"Past performance does not guarantee future results\\."
) + FOOTER

LOCKDOWN_NOTICE = (
"🚨 *CAUTION*: A high\\-impact news event is scheduled for release shortly\\. To protect capital from extreme volatility, all signal generation is paused\\.\n"
"We will resume analysis 30 minutes after the event\\.\n"
"The market is currently consolidating post\\-news\\. I am actively analyzing the charts, waiting for a clear structure and a high\\-probability *migosconcept\\$* setup to form\\.\n"
"*PATIENCE ✰ DISCIPLINE ✰ RISK MANAGEMENT*"
) + FOOTER

COOLDOWN_MSG = (
"Dear {name}, we've hit a few consecutive losses\\. To protect your capital and avoid unfavorable market conditions, "
"I will be pausing trading on your account for today\\. We will resume with fresh analysis tomorrow\\.\n"
"*PATIENCE ✰ DISCIPLINE ✰ RISK MANAGEMENT*"
) + FOOTER
